import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import {
  buildApp,
  markdownDirectoryReader,
  projectApp,
} from "@emsenn/organizing-with-the-semantic-web/semantic-site-server";
import { SITE_CONFIG } from "../src/server.ts";

const siteRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const projectionRoot = join(siteRoot, ".tmp", "worker-projection");
const app = buildApp(markdownDirectoryReader(), SITE_CONFIG);

await projectApp(app, projectionRoot, {
  baseUrl: SITE_CONFIG.baseUrl,
  clean: true,
  entryPaths: ["/market", "/site.json"],
});

const assets = Object.fromEntries(files(projectionRoot).map((path) => [
  `/${relative(projectionRoot, path).replaceAll("\\", "/")}`,
  readFileSync(path, "utf8"),
]));

const source = `// Generated by scripts/build-worker.mjs from the canonical semantic-site application.\n`
  + `// Do not hand-edit this projection.\n`
  + `const assets = ${JSON.stringify(assets)};\n`
  + `const types = ${JSON.stringify(contentTypes())};\n`
  + `function assetPath(pathname) {\n`
  + `  if (pathname === "/") return "/index.html";\n`
  + `  const clean = pathname.replace(/\\/$/, "");\n`
  + `  return /\\.[a-z0-9]+$/i.test(clean) ? clean : clean + "/index.html";\n`
  + `}\n`
  + `export default { fetch(request) {\n`
  + `  const url = new URL(request.url);\n`
  + `  if (url.hostname === "market.561.group" && url.pathname === "/") url.pathname = "/market";\n`
  + `  if (url.hostname === "561.group" && url.pathname === "/market") return Response.redirect("https://market.561.group/", 308);\n`
  + `  const key = assetPath(url.pathname);\n`
  + `  const body = assets[key];\n`
  + `  if (body === undefined) return new Response("Not found\\n", { status: 404, headers: security("text/plain; charset=utf-8") });\n`
  + `  const type = types[key.slice(key.lastIndexOf("."))] || "application/octet-stream";\n`
  + `  return new Response(body, { status: 200, headers: security(type) });\n`
  + `} };\n`
  + `function security(type) { return {\n`
  + `  "content-type": type, "cache-control": "public, max-age=300",\n`
  + `  "content-security-policy": "default-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'self'; frame-ancestors 'none'; object-src 'none'",\n`
  + `  "strict-transport-security": "max-age=31536000; includeSubDomains",\n`
  + `  "x-content-type-options": "nosniff", "referrer-policy": "no-referrer",\n`
  + `  "x-frame-options": "DENY", "permissions-policy": "geolocation=(), microphone=(), camera=()"\n`
  + `}; }\n`;

writeFileSync(join(siteRoot, "src", "worker.mjs"), source);
process.stdout.write(`${JSON.stringify({ type: "561GroupWorkerProjection", assets: Object.keys(assets).length, target: "src/worker.mjs" })}\n`);

function files(root) {
  return readdirSync(root, { withFileTypes: true }).flatMap((entry) => {
    const path = join(root, entry.name);
    return entry.isDirectory() ? files(path) : [path];
  }).sort();
}

function contentTypes() {
  return {
    ".html": "text/html; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".atom": "application/atom+xml; charset=utf-8",
    ".xml": "application/xml; charset=utf-8",
    ".txt": "text/plain; charset=utf-8",
    ".ttl": "text/turtle; charset=utf-8",
    ".jsonld": "application/ld+json; charset=utf-8",
  };
}
